// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'ffi.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `build_history_prefix`, `build_interaction_text`, `current_timestamp_hex`, `doc_to_dto`, `string_to_category`, `to_provider_config`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `camera_push_frame`

/// Initialize file-based tracing to `{dir}/mobileclaw.log`.
///
/// Safe to call multiple times — subsequent calls are silently ignored by
/// `try_init()`.  Creates `dir` if it does not exist.
Future<void> initFileLogging({required String dir}) =>
    MobileclawCoreBridge.instance.api.crateFfiInitFileLogging(dir: dir);

/// Probe an LLM provider for reachability without creating a full session.
/// Returns a `ProbeResultDto` indicating whether the provider is reachable.
Future<ProbeResultDto> providerProbe({
  required ProviderConfigDto config,
  String? apiKey,
}) => MobileclawCoreBridge.instance.api.crateFfiProviderProbe(
  config: config,
  apiKey: apiKey,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AgentSession>>
abstract class AgentSession implements RustOpaqueInterface {
  /// Phase 1 scaffold: return pending camera alerts.
  /// Phase 2: replaces this with a real FRB stream backed by an mpsc channel.
  List<CameraAlert> cameraAlertStream();

  /// Return the ring buffer's current occupancy and latest frame ID.
  /// Phase 1 (VecDeque-backed): returns (len, capacity, latest_frame_id_or_0).
  /// Phase 2 (mmap-backed): returns (slot_count, capacity, offset_of_latest).
  Future<(BigInt, BigInt, BigInt)> cameraGetMmapInfo();

  /// Query whether the camera has been authorized.
  Future<bool> cameraIsAuthorized();

  /// Push a camera frame into the ring buffer.
  ///
  /// Safe FRB-managed instance method. Auto-sets `camera_authorized = true` on success.
  /// Use this from Dart; the free function `camera_push_frame` is `#[frb(skip)]`.
  Future<bool> cameraPushFrameDart({
    required List<int> jpeg,
    required BigInt frameId,
    required BigInt timestampMs,
    required int width,
    required int height,
  });

  /// Manually set camera authorization state.
  /// Usually Dart does not need to call this — authorization auto-enables
  /// on the first `camera_push_frame` call.
  Future<void> cameraSetAuthorized({required bool authorized});

  /// Phase 2 scaffold: start a background camera monitor.
  /// Returns a monitor ID that can be used to stop it later.
  Future<String> cameraStartMonitor({
    required String scenario,
    required int framesPerCheck,
    required int checkIntervalMs,
  });

  /// Phase 2 scaffold: stop a running camera monitor.
  Future<bool> cameraStopMonitor({required String monitorId});

  /// Send a user message and return all events produced by one agent turn.
  Future<List<AgentEventDto>> chat({
    required String input,
    required String system,
  });

  /// Create a new agent session.
  ///
  /// If `skills_dir` is set, the directory must exist and be readable or `create()` will return an error.
  static Future<AgentSession> create({required AgentConfig config}) =>
      MobileclawCoreBridge.instance.api.crateFfiAgentSessionCreate(
        config: config,
      );

  /// Delete an email account and its stored password.
  Future<void> emailAccountDelete({required String id});

  /// Load an email account's configuration. Returns None if the account does not exist.
  /// The password is NOT returned — only the non-secret config fields.
  Future<EmailAccountDto?> emailAccountLoad({required String id});

  /// Save an email account configuration and its password.
  /// The password is encrypted with AES-256-GCM before storage.
  /// After this call, the password cannot be retrieved in plaintext via any FFI method.
  Future<void> emailAccountSave({
    required EmailAccountDto dto,
    required String password,
  });

  /// Return a snapshot of the conversation history.
  Future<List<MessageDto>> history();

  /// Load skills from a directory and replace the current skill manager.
  Future<void> loadSkillsFromDir({required String dir});

  /// Return the total number of memory documents.
  Future<BigInt> memoryCount();

  /// Delete a memory document. Returns true if it existed.
  Future<bool> memoryForget({required String path});

  /// Retrieve a single memory document by path.
  Future<MemoryDocDto?> memoryGet({required String path});

  /// Search the memory database and return ranked results.
  Future<List<SearchResultDto>> memoryRecall({
    required String query,
    required BigInt limit,
    String? category,
    BigInt? since,
    BigInt? until,
  });

  /// Store a document in the memory database.
  Future<MemoryDocDto> memoryStore({
    required String path,
    required String content,
    required String category,
  });

  /// Delete a provider config (and its API key via ON DELETE CASCADE).
  Future<void> providerDelete({required String id});

  /// Return the active provider config, or `None` if no active provider is set.
  Future<ProviderConfigDto?> providerGetActive();

  /// Return all stored provider configs as DTOs.
  Future<List<ProviderConfigDto>> providerList();

  /// Save (upsert) a provider config and optionally store its API key encrypted.
  Future<void> providerSave({
    required ProviderConfigDto config,
    String? apiKey,
  });

  /// Set the active provider by ID. Returns an error if the provider does not exist.
  Future<void> providerSetActive({required String id});

  /// Delete a saved session file. Path is validated against session_dir.
  /// Returns true if the file existed and was deleted.
  Future<bool> sessionDelete({required String filePath});

  /// List all saved sessions in the configured session_dir.
  /// Returns an empty vec if session_dir is not configured.
  Future<List<SessionEntryDto>> sessionList();

  /// Load a session from a JSONL file. Replaces current history.
  /// Returns the number of messages loaded.
  Future<BigInt> sessionLoad({required String filePath});

  /// Save the current conversation history to a session file.
  /// Returns the absolute path of the saved file, or an error if session_dir is not configured.
  Future<String> sessionSave();

  /// Return the loaded skills as DTOs.
  Future<List<SkillManifestDto>> skills();
}

/// Configuration passed from Dart when creating a new agent session.
class AgentConfig {
  final String? apiKey;
  final String dbPath;
  final String secretsDbPath;
  final Uint8List encryptionKey;
  final String sandboxDir;
  final List<String> httpAllowlist;
  final String? model;
  final String? skillsDir;

  /// Directory for log files. When `Some`, `mobileclaw.log` is written there.
  /// Platform guidance:
  ///   Android — pass `context.getFilesDir().absolutePath` (or Flutter's
  ///             `getApplicationSupportDirectory()`)
  ///   iOS     — pass `FileManager.default.urls(.applicationSupportDirectory)[0].path`
  ///             (or Flutter's `getApplicationSupportDirectory()`)
  ///   CLI     — leave as `None`; the CLI calls its own `init_logging()` instead.
  /// When `None`, tracing output goes wherever the caller already registered a
  /// subscriber (no-op if none was registered).
  final String? logDir;

  /// Directory for JSONL session transcripts.
  /// When set, each `chat()` call persists the full conversation history.
  /// Platform guidance: pass a writable directory inside the app's sandbox.
  final String? sessionDir;

  /// Maximum context window tokens (default: 200_000 for Claude Sonnet 4.6).
  /// Controls when context pruning triggers.
  final int? contextWindow;

  /// Maximum messages in history before count-based prune fires. Default: 100.
  final int? maxSessionMessages;

  /// Number of frames to read per camera_capture call. Default: 5.
  final int? cameraFramesPerCapture;

  /// Maximum frames allowed per single capture. Default: 16.
  final int? cameraMaxFramesPerCapture;

  /// Ring buffer capacity for camera frames. Default: 16.
  final int? cameraRingBufferCapacity;

  const AgentConfig({
    this.apiKey,
    required this.dbPath,
    required this.secretsDbPath,
    required this.encryptionKey,
    required this.sandboxDir,
    required this.httpAllowlist,
    this.model,
    this.skillsDir,
    this.logDir,
    this.sessionDir,
    this.contextWindow,
    this.maxSessionMessages,
    this.cameraFramesPerCapture,
    this.cameraMaxFramesPerCapture,
    this.cameraRingBufferCapacity,
  });

  @override
  int get hashCode =>
      apiKey.hashCode ^
      dbPath.hashCode ^
      secretsDbPath.hashCode ^
      encryptionKey.hashCode ^
      sandboxDir.hashCode ^
      httpAllowlist.hashCode ^
      model.hashCode ^
      skillsDir.hashCode ^
      logDir.hashCode ^
      sessionDir.hashCode ^
      contextWindow.hashCode ^
      maxSessionMessages.hashCode ^
      cameraFramesPerCapture.hashCode ^
      cameraMaxFramesPerCapture.hashCode ^
      cameraRingBufferCapacity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentConfig &&
          runtimeType == other.runtimeType &&
          apiKey == other.apiKey &&
          dbPath == other.dbPath &&
          secretsDbPath == other.secretsDbPath &&
          encryptionKey == other.encryptionKey &&
          sandboxDir == other.sandboxDir &&
          httpAllowlist == other.httpAllowlist &&
          model == other.model &&
          skillsDir == other.skillsDir &&
          logDir == other.logDir &&
          sessionDir == other.sessionDir &&
          contextWindow == other.contextWindow &&
          maxSessionMessages == other.maxSessionMessages &&
          cameraFramesPerCapture == other.cameraFramesPerCapture &&
          cameraMaxFramesPerCapture == other.cameraMaxFramesPerCapture &&
          cameraRingBufferCapacity == other.cameraRingBufferCapacity;
}

@freezed
sealed class AgentEventDto with _$AgentEventDto {
  const AgentEventDto._();

  const factory AgentEventDto.textDelta({required String text}) =
      AgentEventDto_TextDelta;
  const factory AgentEventDto.toolCall({required String name}) =
      AgentEventDto_ToolCall;
  const factory AgentEventDto.toolResult({
    required String name,
    required bool success,
  }) = AgentEventDto_ToolResult;

  /// Context-window observability snapshot emitted once per chat() turn.
  const factory AgentEventDto.contextStats({
    required BigInt tokensBeforeTurn,
    required BigInt tokensAfterPrune,
    required BigInt messagesPruned,
    required BigInt historyLen,
    required BigInt pruningThreshold,
  }) = AgentEventDto_ContextStats;

  /// One-sentence summary of the completed interaction, stored permanently.
  const factory AgentEventDto.turnSummary({required String summary}) =
      AgentEventDto_TurnSummary;

  /// Camera access has not been authorized. Dart should show a permission dialog.
  const factory AgentEventDto.cameraAuthRequired() =
      AgentEventDto_CameraAuthRequired;
  const factory AgentEventDto.done() = AgentEventDto_Done;
}

/// An alert emitted by the background camera monitor when something noteworthy is detected.
class CameraAlert {
  final String summary;
  final BigInt frameId;
  final BigInt timestampMs;

  const CameraAlert({
    required this.summary,
    required this.frameId,
    required this.timestampMs,
  });

  @override
  int get hashCode =>
      summary.hashCode ^ frameId.hashCode ^ timestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CameraAlert &&
          runtimeType == other.runtimeType &&
          summary == other.summary &&
          frameId == other.frameId &&
          timestampMs == other.timestampMs;
}

/// Email account configuration DTO (no password — password is stored encrypted in SecretStore).
class EmailAccountDto {
  final String id;
  final String smtpHost;
  final int smtpPort;
  final String imapHost;
  final int imapPort;
  final String username;

  const EmailAccountDto({
    required this.id,
    required this.smtpHost,
    required this.smtpPort,
    required this.imapHost,
    required this.imapPort,
    required this.username,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      smtpHost.hashCode ^
      smtpPort.hashCode ^
      imapHost.hashCode ^
      imapPort.hashCode ^
      username.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EmailAccountDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          smtpHost == other.smtpHost &&
          smtpPort == other.smtpPort &&
          imapHost == other.imapHost &&
          imapPort == other.imapPort &&
          username == other.username;
}

/// A stored memory document.
class MemoryDocDto {
  final String id;
  final String path;
  final String content;
  final String category;
  final BigInt createdAt;
  final BigInt updatedAt;

  const MemoryDocDto({
    required this.id,
    required this.path,
    required this.content,
    required this.category,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      path.hashCode ^
      content.hashCode ^
      category.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemoryDocDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          path == other.path &&
          content == other.content &&
          category == other.category &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// A chat history entry.
class MessageDto {
  final String role;
  final String content;

  const MessageDto({required this.role, required this.content});

  @override
  int get hashCode => role.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageDto &&
          runtimeType == other.runtimeType &&
          role == other.role &&
          content == other.content;
}

/// Result of a connectivity probe against an LLM provider.
class ProbeResultDto {
  final bool ok;
  final BigInt latencyMs;
  final bool degraded;
  final String? error;

  const ProbeResultDto({
    required this.ok,
    required this.latencyMs,
    required this.degraded,
    this.error,
  });

  @override
  int get hashCode =>
      ok.hashCode ^ latencyMs.hashCode ^ degraded.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProbeResultDto &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          latencyMs == other.latencyMs &&
          degraded == other.degraded &&
          error == other.error;
}

/// LLM provider configuration DTO.
class ProviderConfigDto {
  final String id;
  final String name;
  final String protocol;
  final String baseUrl;
  final String model;
  final PlatformInt64 createdAt;

  const ProviderConfigDto({
    required this.id,
    required this.name,
    required this.protocol,
    required this.baseUrl,
    required this.model,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      protocol.hashCode ^
      baseUrl.hashCode ^
      model.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProviderConfigDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          protocol == other.protocol &&
          baseUrl == other.baseUrl &&
          model == other.model &&
          createdAt == other.createdAt;
}

/// A memory search result.
class SearchResultDto {
  final MemoryDocDto doc;
  final double score;

  const SearchResultDto({required this.doc, required this.score});

  @override
  int get hashCode => doc.hashCode ^ score.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchResultDto &&
          runtimeType == other.runtimeType &&
          doc == other.doc &&
          score == other.score;
}

/// Summary of a saved session file — returned by `AgentSession::session_list()`.
class SessionEntryDto {
  final String id;
  final BigInt modified;
  final BigInt messageCount;
  final String filePath;

  const SessionEntryDto({
    required this.id,
    required this.modified,
    required this.messageCount,
    required this.filePath,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      modified.hashCode ^
      messageCount.hashCode ^
      filePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionEntryDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          modified == other.modified &&
          messageCount == other.messageCount &&
          filePath == other.filePath;
}

/// Skill manifest as a plain DTO.
class SkillManifestDto {
  final String name;
  final String description;
  final String trust;
  final List<String> keywords;
  final List<String> allowedTools;

  const SkillManifestDto({
    required this.name,
    required this.description,
    required this.trust,
    required this.keywords,
    required this.allowedTools,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      description.hashCode ^
      trust.hashCode ^
      keywords.hashCode ^
      allowedTools.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SkillManifestDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description &&
          trust == other.trust &&
          keywords == other.keywords &&
          allowedTools == other.allowedTools;
}
