// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'ffi.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `category_to_string`, `doc_to_dto`, `string_to_category`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AgentSession>>
abstract class AgentSession implements RustOpaqueInterface {
  /// Send a user message and return all events produced by one agent turn.
  Future<List<AgentEventDto>> chat({
    required String input,
    required String system,
  });

  /// Create a new agent session.
  ///
  /// If `skills_dir` is set, the directory must exist and be readable or `create()` will return an error.
  static Future<AgentSession> create({required AgentConfig config}) =>
      MobileclawCoreBridge.instance.api.crateFfiAgentSessionCreate(
        config: config,
      );

  /// Return a snapshot of the conversation history.
  Future<List<MessageDto>> history();

  /// Load skills from a directory and replace the current skill manager.
  Future<void> loadSkillsFromDir({required String dir});

  /// Return the total number of memory documents.
  Future<BigInt> memoryCount();

  /// Delete a memory document. Returns true if it existed.
  Future<bool> memoryForget({required String path});

  /// Retrieve a single memory document by path.
  Future<MemoryDocDto?> memoryGet({required String path});

  /// Search the memory database and return ranked results.
  Future<List<SearchResultDto>> memoryRecall({
    required String query,
    required BigInt limit,
    String? category,
    BigInt? since,
    BigInt? until,
  });

  /// Store a document in the memory database.
  Future<MemoryDocDto> memoryStore({
    required String path,
    required String content,
    required String category,
  });

  /// Return the loaded skills as DTOs.
  Future<List<SkillManifestDto>> skills();
}

/// Configuration passed from Dart when creating a new agent session.
class AgentConfig {
  final String apiKey;
  final String dbPath;
  final String sandboxDir;
  final List<String> httpAllowlist;
  final String model;
  final String? skillsDir;

  const AgentConfig({
    required this.apiKey,
    required this.dbPath,
    required this.sandboxDir,
    required this.httpAllowlist,
    required this.model,
    this.skillsDir,
  });

  @override
  int get hashCode =>
      apiKey.hashCode ^
      dbPath.hashCode ^
      sandboxDir.hashCode ^
      httpAllowlist.hashCode ^
      model.hashCode ^
      skillsDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentConfig &&
          runtimeType == other.runtimeType &&
          apiKey == other.apiKey &&
          dbPath == other.dbPath &&
          sandboxDir == other.sandboxDir &&
          httpAllowlist == other.httpAllowlist &&
          model == other.model &&
          skillsDir == other.skillsDir;
}

@freezed
sealed class AgentEventDto with _$AgentEventDto {
  const AgentEventDto._();

  const factory AgentEventDto.textDelta({required String text}) =
      AgentEventDto_TextDelta;
  const factory AgentEventDto.toolCall({required String name}) =
      AgentEventDto_ToolCall;
  const factory AgentEventDto.toolResult({
    required String name,
    required bool success,
  }) = AgentEventDto_ToolResult;
  const factory AgentEventDto.done() = AgentEventDto_Done;
}

/// A stored memory document.
class MemoryDocDto {
  final String id;
  final String path;
  final String content;
  final String category;
  final BigInt createdAt;
  final BigInt updatedAt;

  const MemoryDocDto({
    required this.id,
    required this.path,
    required this.content,
    required this.category,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      path.hashCode ^
      content.hashCode ^
      category.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemoryDocDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          path == other.path &&
          content == other.content &&
          category == other.category &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// A chat history entry.
class MessageDto {
  final String role;
  final String content;

  const MessageDto({required this.role, required this.content});

  @override
  int get hashCode => role.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageDto &&
          runtimeType == other.runtimeType &&
          role == other.role &&
          content == other.content;
}

/// A memory search result.
class SearchResultDto {
  final MemoryDocDto doc;
  final double score;

  const SearchResultDto({required this.doc, required this.score});

  @override
  int get hashCode => doc.hashCode ^ score.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchResultDto &&
          runtimeType == other.runtimeType &&
          doc == other.doc &&
          score == other.score;
}

/// Skill manifest as a plain DTO.
class SkillManifestDto {
  final String name;
  final String description;
  final String trust;
  final List<String> keywords;
  final List<String> allowedTools;

  const SkillManifestDto({
    required this.name,
    required this.description,
    required this.trust,
    required this.keywords,
    required this.allowedTools,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      description.hashCode ^
      trust.hashCode ^
      keywords.hashCode ^
      allowedTools.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SkillManifestDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description &&
          trust == other.trust &&
          keywords == other.keywords &&
          allowedTools == other.allowedTools;
}
