// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'ffi.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `category_to_string`, `doc_to_dto`, `string_to_category`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AgentSession>>
abstract class AgentSession implements RustOpaqueInterface {
  /// Delete an email account and its encrypted password from the secret store.
  Future<void> emailAccountDelete({required String id});

  /// Load an email account config. Returns null if the account does not exist.
  /// The password is NOT returned — only config fields.
  Future<EmailAccountDtoFfi?> emailAccountLoad({required String id});

  /// Save an email account config and encrypt its password via AES-256-GCM.
  Future<void> emailAccountSave({
    required EmailAccountDtoFfi dto,
    required String password,
  });
  /// Send a user message and return all events produced by one agent turn.
  Future<List<AgentEventDto>> chat({
    required String input,
    required String system,
  });

  /// Create a new agent session.
  ///
  /// If `skills_dir` is set, the directory must exist and be readable or `create()` will return an error.
  static Future<AgentSession> create({required AgentConfig config}) =>
      MobileclawCoreBridge.instance.api.crateFfiAgentSessionCreate(
        config: config,
      );

  /// Return a snapshot of the conversation history.
  Future<List<MessageDto>> history();

  /// Load skills from a directory and replace the current skill manager.
  Future<void> loadSkillsFromDir({required String dir});

  /// Return the total number of memory documents.
  Future<BigInt> memoryCount();

  /// Delete a memory document. Returns true if it existed.
  Future<bool> memoryForget({required String path});

  /// Retrieve a single memory document by path.
  Future<MemoryDocDto?> memoryGet({required String path});

  /// Search the memory database and return ranked results.
  Future<List<SearchResultDto>> memoryRecall({
    required String query,
    required BigInt limit,
    String? category,
    BigInt? since,
    BigInt? until,
  });

  /// Store a document in the memory database.
  Future<MemoryDocDto> memoryStore({
    required String path,
    required String content,
    required String category,
  });

  /// Return the loaded skills as DTOs.
  Future<List<SkillManifestDto>> skills();
}

/// Configuration passed from Dart when creating a new agent session.
class AgentConfig {
  final String apiKey;
  final String dbPath;

  /// Absolute path to the secrets SQLite database (stores AES-encrypted email
  /// credentials and other secrets). Created if it does not exist.
  final String secretsDbPath;

  /// 32-byte AES-256 encryption key for the secrets database.
  ///
  /// On Android: derive from Android Keystore.
  /// On iOS: derive from iOS Keychain.
  /// Use [flutter_secure_storage] to generate and persist the key:
  ///   generate once with Random.secure(), store as base64 under
  ///   key 'mobileclaw.secrets_key', and read on subsequent launches.
  final List<int> encryptionKey;

  final String sandboxDir;
  final List<String> httpAllowlist;
  final String model;
  final String? skillsDir;

  const AgentConfig({
    required this.apiKey,
    required this.dbPath,
    required this.secretsDbPath,
    required this.encryptionKey,
    required this.sandboxDir,
    required this.httpAllowlist,
    required this.model,
    this.skillsDir,
  });

  @override
  int get hashCode =>
      apiKey.hashCode ^
      dbPath.hashCode ^
      secretsDbPath.hashCode ^
      encryptionKey.hashCode ^
      sandboxDir.hashCode ^
      httpAllowlist.hashCode ^
      model.hashCode ^
      skillsDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentConfig &&
          runtimeType == other.runtimeType &&
          apiKey == other.apiKey &&
          dbPath == other.dbPath &&
          secretsDbPath == other.secretsDbPath &&
          encryptionKey == other.encryptionKey &&
          sandboxDir == other.sandboxDir &&
          httpAllowlist == other.httpAllowlist &&
          model == other.model &&
          skillsDir == other.skillsDir;
}

/// Email account configuration DTO for FFI crossing.
/// No password field — by design. The password never travels back to Dart.
class EmailAccountDtoFfi {
  final String id;
  final String smtpHost;
  final int smtpPort;
  final String imapHost;
  final int imapPort;
  final String username;

  const EmailAccountDtoFfi({
    required this.id,
    required this.smtpHost,
    required this.smtpPort,
    required this.imapHost,
    required this.imapPort,
    required this.username,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      smtpHost.hashCode ^
      smtpPort.hashCode ^
      imapHost.hashCode ^
      imapPort.hashCode ^
      username.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EmailAccountDtoFfi &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          smtpHost == other.smtpHost &&
          smtpPort == other.smtpPort &&
          imapHost == other.imapHost &&
          imapPort == other.imapPort &&
          username == other.username;
}

@freezed
sealed class AgentEventDto with _$AgentEventDto {
  const AgentEventDto._();

  const factory AgentEventDto.textDelta({required String text}) =
      AgentEventDto_TextDelta;
  const factory AgentEventDto.toolCall({required String name}) =
      AgentEventDto_ToolCall;
  const factory AgentEventDto.toolResult({
    required String name,
    required bool success,
  }) = AgentEventDto_ToolResult;
  const factory AgentEventDto.done() = AgentEventDto_Done;
}

/// A stored memory document.
class MemoryDocDto {
  final String id;
  final String path;
  final String content;
  final String category;
  final BigInt createdAt;
  final BigInt updatedAt;

  const MemoryDocDto({
    required this.id,
    required this.path,
    required this.content,
    required this.category,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      path.hashCode ^
      content.hashCode ^
      category.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemoryDocDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          path == other.path &&
          content == other.content &&
          category == other.category &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// A chat history entry.
class MessageDto {
  final String role;
  final String content;

  const MessageDto({required this.role, required this.content});

  @override
  int get hashCode => role.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageDto &&
          runtimeType == other.runtimeType &&
          role == other.role &&
          content == other.content;
}

/// A memory search result.
class SearchResultDto {
  final MemoryDocDto doc;
  final double score;

  const SearchResultDto({required this.doc, required this.score});

  @override
  int get hashCode => doc.hashCode ^ score.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchResultDto &&
          runtimeType == other.runtimeType &&
          doc == other.doc &&
          score == other.score;
}

/// Skill manifest as a plain DTO.
class SkillManifestDto {
  final String name;
  final String description;
  final String trust;
  final List<String> keywords;
  final List<String> allowedTools;

  const SkillManifestDto({
    required this.name,
    required this.description,
    required this.trust,
    required this.keywords,
    required this.allowedTools,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      description.hashCode ^
      trust.hashCode ^
      keywords.hashCode ^
      allowedTools.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SkillManifestDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description &&
          trust == other.trust &&
          keywords == other.keywords &&
          allowedTools == other.allowedTools;
}
