// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'ffi.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class MobileclawCoreBridge
    extends
        BaseEntrypoint<
          MobileclawCoreBridgeApi,
          MobileclawCoreBridgeApiImpl,
          MobileclawCoreBridgeWire
        > {
  @internal
  static final instance = MobileclawCoreBridge._();

  MobileclawCoreBridge._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    MobileclawCoreBridgeApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required MobileclawCoreBridgeApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<MobileclawCoreBridgeApiImpl, MobileclawCoreBridgeWire>
  get apiImplConstructor => MobileclawCoreBridgeApiImpl.new;

  @override
  WireConstructor<MobileclawCoreBridgeWire> get wireConstructor =>
      MobileclawCoreBridgeWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1934789171;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'mobileclaw_core',
        ioDirectory: '../../../mobileclaw-core/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class MobileclawCoreBridgeApi extends BaseApi {
  Future<ClawResultVecAgentEventDto> crateFfiAgentSessionChat({
    required AgentSession that,
    required String input,
    required String system,
  });

  Future<ClawResultAgentSession> crateFfiAgentSessionCreate({
    required AgentConfig config,
  });

  Future<List<MessageDto>> crateFfiAgentSessionHistory({
    required AgentSession that,
  });

  Future<ClawResult> crateFfiAgentSessionLoadSkillsFromDir({
    required AgentSession that,
    required String dir,
  });

  Future<ClawResultUsize> crateFfiAgentSessionMemoryCount({
    required AgentSession that,
  });

  Future<ClawResultBool> crateFfiAgentSessionMemoryForget({
    required AgentSession that,
    required String path,
  });

  Future<ClawResultOptionMemoryDocDto> crateFfiAgentSessionMemoryGet({
    required AgentSession that,
    required String path,
  });

  Future<ClawResultVecSearchResultDto> crateFfiAgentSessionMemoryRecall({
    required AgentSession that,
    required String query,
    required BigInt limit,
    String? category,
    BigInt? since,
    BigInt? until,
  });

  Future<ClawResultMemoryDocDto> crateFfiAgentSessionMemoryStore({
    required AgentSession that,
    required String path,
    required String content,
    required String category,
  });

  Future<List<SkillManifestDto>> crateFfiAgentSessionSkills({
    required AgentSession that,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AgentSession;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AgentSession;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_AgentSessionPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ClawResult;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ClawResult;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ClawResultPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ClawResultAgentSession;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ClawResultAgentSession;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ClawResultAgentSessionPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ClawResultMemoryDocDto;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ClawResultMemoryDocDto;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ClawResultMemoryDocDtoPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ClawResultOptionMemoryDocDto;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ClawResultOptionMemoryDocDto;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ClawResultOptionMemoryDocDtoPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ClawResultVecAgentEventDto;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ClawResultVecAgentEventDto;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ClawResultVecAgentEventDtoPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ClawResultVecSearchResultDto;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ClawResultVecSearchResultDto;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ClawResultVecSearchResultDtoPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ClawResultBool;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ClawResultBool;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ClawResultBoolPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ClawResultUsize;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ClawResultUsize;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ClawResultUsizePtr;
}

class MobileclawCoreBridgeApiImpl extends MobileclawCoreBridgeApiImplPlatform
    implements MobileclawCoreBridgeApi {
  MobileclawCoreBridgeApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<ClawResultVecAgentEventDto> crateFfiAgentSessionChat({
    required AgentSession that,
    required String input,
    required String system,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
            that,
            serializer,
          );
          sse_encode_String(input, serializer);
          sse_encode_String(system, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultVecAgentEventDto,
          decodeErrorData: null,
        ),
        constMeta: kCrateFfiAgentSessionChatConstMeta,
        argValues: [that, input, system],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiAgentSessionChatConstMeta => const TaskConstMeta(
    debugName: "AgentSession_chat",
    argNames: ["that", "input", "system"],
  );

  @override
  Future<ClawResultAgentSession> crateFfiAgentSessionCreate({
    required AgentConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_agent_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultAgentSession,
          decodeErrorData: null,
        ),
        constMeta: kCrateFfiAgentSessionCreateConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiAgentSessionCreateConstMeta => const TaskConstMeta(
    debugName: "AgentSession_create",
    argNames: ["config"],
  );

  @override
  Future<List<MessageDto>> crateFfiAgentSessionHistory({
    required AgentSession that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_message_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateFfiAgentSessionHistoryConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiAgentSessionHistoryConstMeta =>
      const TaskConstMeta(
        debugName: "AgentSession_history",
        argNames: ["that"],
      );

  @override
  Future<ClawResult> crateFfiAgentSessionLoadSkillsFromDir({
    required AgentSession that,
    required String dir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
            that,
            serializer,
          );
          sse_encode_String(dir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResult,
          decodeErrorData: null,
        ),
        constMeta: kCrateFfiAgentSessionLoadSkillsFromDirConstMeta,
        argValues: [that, dir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiAgentSessionLoadSkillsFromDirConstMeta =>
      const TaskConstMeta(
        debugName: "AgentSession_load_skills_from_dir",
        argNames: ["that", "dir"],
      );

  @override
  Future<ClawResultUsize> crateFfiAgentSessionMemoryCount({
    required AgentSession that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultusize,
          decodeErrorData: null,
        ),
        constMeta: kCrateFfiAgentSessionMemoryCountConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiAgentSessionMemoryCountConstMeta =>
      const TaskConstMeta(
        debugName: "AgentSession_memory_count",
        argNames: ["that"],
      );

  @override
  Future<ClawResultBool> crateFfiAgentSessionMemoryForget({
    required AgentSession that,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultbool,
          decodeErrorData: null,
        ),
        constMeta: kCrateFfiAgentSessionMemoryForgetConstMeta,
        argValues: [that, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiAgentSessionMemoryForgetConstMeta =>
      const TaskConstMeta(
        debugName: "AgentSession_memory_forget",
        argNames: ["that", "path"],
      );

  @override
  Future<ClawResultOptionMemoryDocDto> crateFfiAgentSessionMemoryGet({
    required AgentSession that,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultOptionMemoryDocDto,
          decodeErrorData: null,
        ),
        constMeta: kCrateFfiAgentSessionMemoryGetConstMeta,
        argValues: [that, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiAgentSessionMemoryGetConstMeta =>
      const TaskConstMeta(
        debugName: "AgentSession_memory_get",
        argNames: ["that", "path"],
      );

  @override
  Future<ClawResultVecSearchResultDto> crateFfiAgentSessionMemoryRecall({
    required AgentSession that,
    required String query,
    required BigInt limit,
    String? category,
    BigInt? since,
    BigInt? until,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
            that,
            serializer,
          );
          sse_encode_String(query, serializer);
          sse_encode_usize(limit, serializer);
          sse_encode_opt_String(category, serializer);
          sse_encode_opt_box_autoadd_u_64(since, serializer);
          sse_encode_opt_box_autoadd_u_64(until, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultVecSearchResultDto,
          decodeErrorData: null,
        ),
        constMeta: kCrateFfiAgentSessionMemoryRecallConstMeta,
        argValues: [that, query, limit, category, since, until],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiAgentSessionMemoryRecallConstMeta =>
      const TaskConstMeta(
        debugName: "AgentSession_memory_recall",
        argNames: ["that", "query", "limit", "category", "since", "until"],
      );

  @override
  Future<ClawResultMemoryDocDto> crateFfiAgentSessionMemoryStore({
    required AgentSession that,
    required String path,
    required String content,
    required String category,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          sse_encode_String(content, serializer);
          sse_encode_String(category, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultMemoryDocDto,
          decodeErrorData: null,
        ),
        constMeta: kCrateFfiAgentSessionMemoryStoreConstMeta,
        argValues: [that, path, content, category],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiAgentSessionMemoryStoreConstMeta =>
      const TaskConstMeta(
        debugName: "AgentSession_memory_store",
        argNames: ["that", "path", "content", "category"],
      );

  @override
  Future<List<SkillManifestDto>> crateFfiAgentSessionSkills({
    required AgentSession that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_skill_manifest_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateFfiAgentSessionSkillsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiAgentSessionSkillsConstMeta =>
      const TaskConstMeta(debugName: "AgentSession_skills", argNames: ["that"]);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AgentSession => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AgentSession => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ClawResult => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResult;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ClawResult => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResult;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ClawResultAgentSession => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultAgentSession;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ClawResultAgentSession => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultAgentSession;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ClawResultMemoryDocDto => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultMemoryDocDto;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ClawResultMemoryDocDto => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultMemoryDocDto;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ClawResultOptionMemoryDocDto => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultOptionMemoryDocDto;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ClawResultOptionMemoryDocDto => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultOptionMemoryDocDto;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ClawResultVecAgentEventDto => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultVecAgentEventDto;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ClawResultVecAgentEventDto => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultVecAgentEventDto;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ClawResultVecSearchResultDto => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultVecSearchResultDto;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ClawResultVecSearchResultDto => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultVecSearchResultDto;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ClawResultBool => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultbool;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ClawResultBool => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultbool;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ClawResultUsize => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultusize;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ClawResultUsize => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultusize;

  @protected
  AgentSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AgentSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ClawResult
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResult(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ClawResultImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ClawResultAgentSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultAgentSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ClawResultAgentSessionImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  ClawResultMemoryDocDto
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultMemoryDocDto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ClawResultMemoryDocDtoImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  ClawResultOptionMemoryDocDto
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultOptionMemoryDocDto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ClawResultOptionMemoryDocDtoImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  ClawResultVecAgentEventDto
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultVecAgentEventDto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ClawResultVecAgentEventDtoImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  ClawResultVecSearchResultDto
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultVecSearchResultDto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ClawResultVecSearchResultDtoImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  ClawResultBool
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultbool(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ClawResultBoolImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ClawResultUsize
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultusize(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ClawResultUsizeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AgentSession
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AgentSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AgentSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AgentSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AgentSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AgentSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ClawResult
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResult(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ClawResultImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ClawResultAgentSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultAgentSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ClawResultAgentSessionImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  ClawResultMemoryDocDto
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultMemoryDocDto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ClawResultMemoryDocDtoImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  ClawResultOptionMemoryDocDto
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultOptionMemoryDocDto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ClawResultOptionMemoryDocDtoImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  ClawResultVecAgentEventDto
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultVecAgentEventDto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ClawResultVecAgentEventDtoImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  ClawResultVecSearchResultDto
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultVecSearchResultDto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ClawResultVecSearchResultDtoImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  ClawResultBool
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultbool(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ClawResultBoolImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ClawResultUsize
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultusize(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ClawResultUsizeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AgentConfig dco_decode_agent_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return AgentConfig(
      apiKey: dco_decode_String(arr[0]),
      dbPath: dco_decode_String(arr[1]),
      sandboxDir: dco_decode_String(arr[2]),
      httpAllowlist: dco_decode_list_String(arr[3]),
      model: dco_decode_String(arr[4]),
      skillsDir: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  AgentConfig dco_decode_box_autoadd_agent_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_agent_config(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<MessageDto> dco_decode_list_message_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_message_dto).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SkillManifestDto> dco_decode_list_skill_manifest_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_skill_manifest_dto).toList();
  }

  @protected
  MessageDto dco_decode_message_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MessageDto(
      role: dco_decode_String(arr[0]),
      content: dco_decode_String(arr[1]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  SkillManifestDto dco_decode_skill_manifest_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SkillManifestDto(
      name: dco_decode_String(arr[0]),
      description: dco_decode_String(arr[1]),
      trust: dco_decode_String(arr[2]),
      keywords: dco_decode_list_String(arr[3]),
      allowedTools: dco_decode_list_String(arr[4]),
    );
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AgentSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AgentSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ClawResult
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResult(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ClawResultImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ClawResultAgentSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultAgentSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ClawResultAgentSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ClawResultMemoryDocDto
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultMemoryDocDto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ClawResultMemoryDocDtoImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ClawResultOptionMemoryDocDto
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultOptionMemoryDocDto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ClawResultOptionMemoryDocDtoImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ClawResultVecAgentEventDto
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultVecAgentEventDto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ClawResultVecAgentEventDtoImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ClawResultVecSearchResultDto
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultVecSearchResultDto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ClawResultVecSearchResultDtoImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ClawResultBool
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultbool(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ClawResultBoolImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ClawResultUsize
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultusize(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ClawResultUsizeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AgentSession
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AgentSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AgentSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AgentSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AgentSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AgentSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ClawResult
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResult(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ClawResultImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ClawResultAgentSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultAgentSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ClawResultAgentSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ClawResultMemoryDocDto
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultMemoryDocDto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ClawResultMemoryDocDtoImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ClawResultOptionMemoryDocDto
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultOptionMemoryDocDto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ClawResultOptionMemoryDocDtoImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ClawResultVecAgentEventDto
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultVecAgentEventDto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ClawResultVecAgentEventDtoImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ClawResultVecSearchResultDto
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultVecSearchResultDto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ClawResultVecSearchResultDtoImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ClawResultBool
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultbool(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ClawResultBoolImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ClawResultUsize
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultusize(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ClawResultUsizeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AgentConfig sse_decode_agent_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_apiKey = sse_decode_String(deserializer);
    var var_dbPath = sse_decode_String(deserializer);
    var var_sandboxDir = sse_decode_String(deserializer);
    var var_httpAllowlist = sse_decode_list_String(deserializer);
    var var_model = sse_decode_String(deserializer);
    var var_skillsDir = sse_decode_opt_String(deserializer);
    return AgentConfig(
      apiKey: var_apiKey,
      dbPath: var_dbPath,
      sandboxDir: var_sandboxDir,
      httpAllowlist: var_httpAllowlist,
      model: var_model,
      skillsDir: var_skillsDir,
    );
  }

  @protected
  AgentConfig sse_decode_box_autoadd_agent_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_agent_config(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<MessageDto> sse_decode_list_message_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MessageDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_message_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SkillManifestDto> sse_decode_list_skill_manifest_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SkillManifestDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_skill_manifest_dto(deserializer));
    }
    return ans_;
  }

  @protected
  MessageDto sse_decode_message_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_role = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    return MessageDto(role: var_role, content: var_content);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SkillManifestDto sse_decode_skill_manifest_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_trust = sse_decode_String(deserializer);
    var var_keywords = sse_decode_list_String(deserializer);
    var var_allowedTools = sse_decode_list_String(deserializer);
    return SkillManifestDto(
      name: var_name,
      description: var_description,
      trust: var_trust,
      keywords: var_keywords,
      allowedTools: var_allowedTools,
    );
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    AgentSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AgentSessionImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResult(
    ClawResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ClawResultImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultAgentSession(
    ClawResultAgentSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ClawResultAgentSessionImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultMemoryDocDto(
    ClawResultMemoryDocDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ClawResultMemoryDocDtoImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultOptionMemoryDocDto(
    ClawResultOptionMemoryDocDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ClawResultOptionMemoryDocDtoImpl).frbInternalSseEncode(
        move: true,
      ),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultVecAgentEventDto(
    ClawResultVecAgentEventDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ClawResultVecAgentEventDtoImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultVecSearchResultDto(
    ClawResultVecSearchResultDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ClawResultVecSearchResultDtoImpl).frbInternalSseEncode(
        move: true,
      ),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultbool(
    ClawResultBool self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ClawResultBoolImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultusize(
    ClawResultUsize self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ClawResultUsizeImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    AgentSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AgentSessionImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    AgentSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AgentSessionImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    AgentSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AgentSessionImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResult(
    ClawResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ClawResultImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultAgentSession(
    ClawResultAgentSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ClawResultAgentSessionImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultMemoryDocDto(
    ClawResultMemoryDocDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ClawResultMemoryDocDtoImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultOptionMemoryDocDto(
    ClawResultOptionMemoryDocDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ClawResultOptionMemoryDocDtoImpl).frbInternalSseEncode(
        move: null,
      ),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultVecAgentEventDto(
    ClawResultVecAgentEventDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ClawResultVecAgentEventDtoImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultVecSearchResultDto(
    ClawResultVecSearchResultDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ClawResultVecSearchResultDtoImpl).frbInternalSseEncode(
        move: null,
      ),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultbool(
    ClawResultBool self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ClawResultBoolImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClawResultusize(
    ClawResultUsize self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ClawResultUsizeImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_agent_config(AgentConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.apiKey, serializer);
    sse_encode_String(self.dbPath, serializer);
    sse_encode_String(self.sandboxDir, serializer);
    sse_encode_list_String(self.httpAllowlist, serializer);
    sse_encode_String(self.model, serializer);
    sse_encode_opt_String(self.skillsDir, serializer);
  }

  @protected
  void sse_encode_box_autoadd_agent_config(
    AgentConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_agent_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_message_dto(
    List<MessageDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_message_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_skill_manifest_dto(
    List<SkillManifestDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_skill_manifest_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_message_dto(MessageDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.role, serializer);
    sse_encode_String(self.content, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_skill_manifest_dto(
    SkillManifestDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_String(self.trust, serializer);
    sse_encode_list_String(self.keywords, serializer);
    sse_encode_list_String(self.allowedTools, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class AgentSessionImpl extends RustOpaque implements AgentSession {
  // Not to be used by end users
  AgentSessionImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  AgentSessionImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: MobileclawCoreBridge
        .instance
        .api
        .rust_arc_increment_strong_count_AgentSession,
    rustArcDecrementStrongCount: MobileclawCoreBridge
        .instance
        .api
        .rust_arc_decrement_strong_count_AgentSession,
    rustArcDecrementStrongCountPtr: MobileclawCoreBridge
        .instance
        .api
        .rust_arc_decrement_strong_count_AgentSessionPtr,
  );

  /// Send a user message and return all events produced by one agent turn.
  Future<ClawResultVecAgentEventDto> chat({
    required String input,
    required String system,
  }) => MobileclawCoreBridge.instance.api.crateFfiAgentSessionChat(
    that: this,
    input: input,
    system: system,
  );

  /// Return a snapshot of the conversation history.
  Future<List<MessageDto>> history() =>
      MobileclawCoreBridge.instance.api.crateFfiAgentSessionHistory(that: this);

  /// Load skills from a directory and replace the current skill manager.
  Future<ClawResult> loadSkillsFromDir({required String dir}) =>
      MobileclawCoreBridge.instance.api.crateFfiAgentSessionLoadSkillsFromDir(
        that: this,
        dir: dir,
      );

  /// Return the total number of memory documents.
  Future<ClawResultUsize> memoryCount() => MobileclawCoreBridge.instance.api
      .crateFfiAgentSessionMemoryCount(that: this);

  /// Delete a memory document. Returns true if it existed.
  Future<ClawResultBool> memoryForget({required String path}) =>
      MobileclawCoreBridge.instance.api.crateFfiAgentSessionMemoryForget(
        that: this,
        path: path,
      );

  /// Retrieve a single memory document by path.
  Future<ClawResultOptionMemoryDocDto> memoryGet({required String path}) =>
      MobileclawCoreBridge.instance.api.crateFfiAgentSessionMemoryGet(
        that: this,
        path: path,
      );

  /// Search the memory database and return ranked results.
  Future<ClawResultVecSearchResultDto> memoryRecall({
    required String query,
    required BigInt limit,
    String? category,
    BigInt? since,
    BigInt? until,
  }) => MobileclawCoreBridge.instance.api.crateFfiAgentSessionMemoryRecall(
    that: this,
    query: query,
    limit: limit,
    category: category,
    since: since,
    until: until,
  );

  /// Store a document in the memory database.
  Future<ClawResultMemoryDocDto> memoryStore({
    required String path,
    required String content,
    required String category,
  }) => MobileclawCoreBridge.instance.api.crateFfiAgentSessionMemoryStore(
    that: this,
    path: path,
    content: content,
    category: category,
  );

  /// Return the loaded skills as DTOs.
  Future<List<SkillManifestDto>> skills() =>
      MobileclawCoreBridge.instance.api.crateFfiAgentSessionSkills(that: this);
}

@sealed
class ClawResultAgentSessionImpl extends RustOpaque
    implements ClawResultAgentSession {
  // Not to be used by end users
  ClawResultAgentSessionImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ClawResultAgentSessionImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: MobileclawCoreBridge
        .instance
        .api
        .rust_arc_increment_strong_count_ClawResultAgentSession,
    rustArcDecrementStrongCount: MobileclawCoreBridge
        .instance
        .api
        .rust_arc_decrement_strong_count_ClawResultAgentSession,
    rustArcDecrementStrongCountPtr: MobileclawCoreBridge
        .instance
        .api
        .rust_arc_decrement_strong_count_ClawResultAgentSessionPtr,
  );
}

@sealed
class ClawResultBoolImpl extends RustOpaque implements ClawResultBool {
  // Not to be used by end users
  ClawResultBoolImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ClawResultBoolImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: MobileclawCoreBridge
        .instance
        .api
        .rust_arc_increment_strong_count_ClawResultBool,
    rustArcDecrementStrongCount: MobileclawCoreBridge
        .instance
        .api
        .rust_arc_decrement_strong_count_ClawResultBool,
    rustArcDecrementStrongCountPtr: MobileclawCoreBridge
        .instance
        .api
        .rust_arc_decrement_strong_count_ClawResultBoolPtr,
  );
}

@sealed
class ClawResultImpl extends RustOpaque implements ClawResult {
  // Not to be used by end users
  ClawResultImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ClawResultImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: MobileclawCoreBridge
        .instance
        .api
        .rust_arc_increment_strong_count_ClawResult,
    rustArcDecrementStrongCount: MobileclawCoreBridge
        .instance
        .api
        .rust_arc_decrement_strong_count_ClawResult,
    rustArcDecrementStrongCountPtr: MobileclawCoreBridge
        .instance
        .api
        .rust_arc_decrement_strong_count_ClawResultPtr,
  );
}

@sealed
class ClawResultMemoryDocDtoImpl extends RustOpaque
    implements ClawResultMemoryDocDto {
  // Not to be used by end users
  ClawResultMemoryDocDtoImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ClawResultMemoryDocDtoImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: MobileclawCoreBridge
        .instance
        .api
        .rust_arc_increment_strong_count_ClawResultMemoryDocDto,
    rustArcDecrementStrongCount: MobileclawCoreBridge
        .instance
        .api
        .rust_arc_decrement_strong_count_ClawResultMemoryDocDto,
    rustArcDecrementStrongCountPtr: MobileclawCoreBridge
        .instance
        .api
        .rust_arc_decrement_strong_count_ClawResultMemoryDocDtoPtr,
  );
}

@sealed
class ClawResultOptionMemoryDocDtoImpl extends RustOpaque
    implements ClawResultOptionMemoryDocDto {
  // Not to be used by end users
  ClawResultOptionMemoryDocDtoImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ClawResultOptionMemoryDocDtoImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: MobileclawCoreBridge
        .instance
        .api
        .rust_arc_increment_strong_count_ClawResultOptionMemoryDocDto,
    rustArcDecrementStrongCount: MobileclawCoreBridge
        .instance
        .api
        .rust_arc_decrement_strong_count_ClawResultOptionMemoryDocDto,
    rustArcDecrementStrongCountPtr: MobileclawCoreBridge
        .instance
        .api
        .rust_arc_decrement_strong_count_ClawResultOptionMemoryDocDtoPtr,
  );
}

@sealed
class ClawResultUsizeImpl extends RustOpaque implements ClawResultUsize {
  // Not to be used by end users
  ClawResultUsizeImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ClawResultUsizeImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: MobileclawCoreBridge
        .instance
        .api
        .rust_arc_increment_strong_count_ClawResultUsize,
    rustArcDecrementStrongCount: MobileclawCoreBridge
        .instance
        .api
        .rust_arc_decrement_strong_count_ClawResultUsize,
    rustArcDecrementStrongCountPtr: MobileclawCoreBridge
        .instance
        .api
        .rust_arc_decrement_strong_count_ClawResultUsizePtr,
  );
}

@sealed
class ClawResultVecAgentEventDtoImpl extends RustOpaque
    implements ClawResultVecAgentEventDto {
  // Not to be used by end users
  ClawResultVecAgentEventDtoImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ClawResultVecAgentEventDtoImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: MobileclawCoreBridge
        .instance
        .api
        .rust_arc_increment_strong_count_ClawResultVecAgentEventDto,
    rustArcDecrementStrongCount: MobileclawCoreBridge
        .instance
        .api
        .rust_arc_decrement_strong_count_ClawResultVecAgentEventDto,
    rustArcDecrementStrongCountPtr: MobileclawCoreBridge
        .instance
        .api
        .rust_arc_decrement_strong_count_ClawResultVecAgentEventDtoPtr,
  );
}

@sealed
class ClawResultVecSearchResultDtoImpl extends RustOpaque
    implements ClawResultVecSearchResultDto {
  // Not to be used by end users
  ClawResultVecSearchResultDtoImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ClawResultVecSearchResultDtoImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: MobileclawCoreBridge
        .instance
        .api
        .rust_arc_increment_strong_count_ClawResultVecSearchResultDto,
    rustArcDecrementStrongCount: MobileclawCoreBridge
        .instance
        .api
        .rust_arc_decrement_strong_count_ClawResultVecSearchResultDto,
    rustArcDecrementStrongCountPtr: MobileclawCoreBridge
        .instance
        .api
        .rust_arc_decrement_strong_count_ClawResultVecSearchResultDtoPtr,
  );
}
