// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'dart:async';
import 'dart:convert';
import 'ffi.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class MobileclawCoreBridgeApiImplPlatform
    extends BaseApiImpl<MobileclawCoreBridgeWire> {
  MobileclawCoreBridgeApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AgentSessionPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  AgentSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    dynamic raw,
  );

  @protected
  AgentSession
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    dynamic raw,
  );

  @protected
  AgentSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    dynamic raw,
  );

  @protected
  AgentSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AgentConfig dco_decode_agent_config(dynamic raw);

  @protected
  AgentEventDto dco_decode_agent_event_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AgentConfig dco_decode_box_autoadd_agent_config(dynamic raw);

  @protected
  EmailAccountDto dco_decode_box_autoadd_email_account_dto(dynamic raw);

  @protected
  MemoryDocDto dco_decode_box_autoadd_memory_doc_dto(dynamic raw);

  @protected
  ProviderConfigDto dco_decode_box_autoadd_provider_config_dto(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  CameraAlert dco_decode_camera_alert(dynamic raw);

  @protected
  EmailAccountDto dco_decode_email_account_dto(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AgentEventDto> dco_decode_list_agent_event_dto(dynamic raw);

  @protected
  List<CameraAlert> dco_decode_list_camera_alert(dynamic raw);

  @protected
  List<MessageDto> dco_decode_list_message_dto(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProviderConfigDto> dco_decode_list_provider_config_dto(dynamic raw);

  @protected
  List<SearchResultDto> dco_decode_list_search_result_dto(dynamic raw);

  @protected
  List<SessionEntryDto> dco_decode_list_session_entry_dto(dynamic raw);

  @protected
  List<SkillManifestDto> dco_decode_list_skill_manifest_dto(dynamic raw);

  @protected
  MemoryDocDto dco_decode_memory_doc_dto(dynamic raw);

  @protected
  MessageDto dco_decode_message_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  EmailAccountDto? dco_decode_opt_box_autoadd_email_account_dto(dynamic raw);

  @protected
  MemoryDocDto? dco_decode_opt_box_autoadd_memory_doc_dto(dynamic raw);

  @protected
  ProviderConfigDto? dco_decode_opt_box_autoadd_provider_config_dto(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  ProbeResultDto dco_decode_probe_result_dto(dynamic raw);

  @protected
  ProviderConfigDto dco_decode_provider_config_dto(dynamic raw);

  @protected
  (BigInt, BigInt, BigInt) dco_decode_record_usize_usize_u_64(dynamic raw);

  @protected
  SearchResultDto dco_decode_search_result_dto(dynamic raw);

  @protected
  SessionEntryDto dco_decode_session_entry_dto(dynamic raw);

  @protected
  SkillManifestDto dco_decode_skill_manifest_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  AgentSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    SseDeserializer deserializer,
  );

  @protected
  AgentSession
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    SseDeserializer deserializer,
  );

  @protected
  AgentSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    SseDeserializer deserializer,
  );

  @protected
  AgentSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AgentConfig sse_decode_agent_config(SseDeserializer deserializer);

  @protected
  AgentEventDto sse_decode_agent_event_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AgentConfig sse_decode_box_autoadd_agent_config(SseDeserializer deserializer);

  @protected
  EmailAccountDto sse_decode_box_autoadd_email_account_dto(
    SseDeserializer deserializer,
  );

  @protected
  MemoryDocDto sse_decode_box_autoadd_memory_doc_dto(
    SseDeserializer deserializer,
  );

  @protected
  ProviderConfigDto sse_decode_box_autoadd_provider_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  CameraAlert sse_decode_camera_alert(SseDeserializer deserializer);

  @protected
  EmailAccountDto sse_decode_email_account_dto(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AgentEventDto> sse_decode_list_agent_event_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<CameraAlert> sse_decode_list_camera_alert(SseDeserializer deserializer);

  @protected
  List<MessageDto> sse_decode_list_message_dto(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProviderConfigDto> sse_decode_list_provider_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<SearchResultDto> sse_decode_list_search_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<SessionEntryDto> sse_decode_list_session_entry_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<SkillManifestDto> sse_decode_list_skill_manifest_dto(
    SseDeserializer deserializer,
  );

  @protected
  MemoryDocDto sse_decode_memory_doc_dto(SseDeserializer deserializer);

  @protected
  MessageDto sse_decode_message_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  EmailAccountDto? sse_decode_opt_box_autoadd_email_account_dto(
    SseDeserializer deserializer,
  );

  @protected
  MemoryDocDto? sse_decode_opt_box_autoadd_memory_doc_dto(
    SseDeserializer deserializer,
  );

  @protected
  ProviderConfigDto? sse_decode_opt_box_autoadd_provider_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  ProbeResultDto sse_decode_probe_result_dto(SseDeserializer deserializer);

  @protected
  ProviderConfigDto sse_decode_provider_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  (BigInt, BigInt, BigInt) sse_decode_record_usize_usize_u_64(
    SseDeserializer deserializer,
  );

  @protected
  SearchResultDto sse_decode_search_result_dto(SseDeserializer deserializer);

  @protected
  SessionEntryDto sse_decode_session_entry_dto(SseDeserializer deserializer);

  @protected
  SkillManifestDto sse_decode_skill_manifest_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    AgentSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    AgentSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    AgentSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    AgentSession self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_agent_config(AgentConfig self, SseSerializer serializer);

  @protected
  void sse_encode_agent_event_dto(AgentEventDto self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_agent_config(
    AgentConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_email_account_dto(
    EmailAccountDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_memory_doc_dto(
    MemoryDocDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_provider_config_dto(
    ProviderConfigDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_camera_alert(CameraAlert self, SseSerializer serializer);

  @protected
  void sse_encode_email_account_dto(
    EmailAccountDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_agent_event_dto(
    List<AgentEventDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_camera_alert(
    List<CameraAlert> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_message_dto(
    List<MessageDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_provider_config_dto(
    List<ProviderConfigDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_search_result_dto(
    List<SearchResultDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_session_entry_dto(
    List<SessionEntryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_skill_manifest_dto(
    List<SkillManifestDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_memory_doc_dto(MemoryDocDto self, SseSerializer serializer);

  @protected
  void sse_encode_message_dto(MessageDto self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_email_account_dto(
    EmailAccountDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_memory_doc_dto(
    MemoryDocDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_provider_config_dto(
    ProviderConfigDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_probe_result_dto(
    ProbeResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_provider_config_dto(
    ProviderConfigDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_usize_usize_u_64(
    (BigInt, BigInt, BigInt) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_search_result_dto(
    SearchResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_entry_dto(
    SessionEntryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_skill_manifest_dto(
    SkillManifestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class MobileclawCoreBridgeWire implements BaseWire {
  MobileclawCoreBridgeWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
        ptr,
      );
}

@JS('wasm_bindgen')
external MobileclawCoreBridgeWasmModule get wasmModule;

@JS()
@anonymous
extension type MobileclawCoreBridgeWasmModule._(JSObject _)
    implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    int ptr,
  );
}
