// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'ffi.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class MobileclawCoreBridge
    extends
        BaseEntrypoint<
          MobileclawCoreBridgeApi,
          MobileclawCoreBridgeApiImpl,
          MobileclawCoreBridgeWire
        > {
  @internal
  static final instance = MobileclawCoreBridge._();

  MobileclawCoreBridge._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    MobileclawCoreBridgeApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required MobileclawCoreBridgeApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<MobileclawCoreBridgeApiImpl, MobileclawCoreBridgeWire>
  get apiImplConstructor => MobileclawCoreBridgeApiImpl.new;

  @override
  WireConstructor<MobileclawCoreBridgeWire> get wireConstructor =>
      MobileclawCoreBridgeWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1462094073;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'mobileclaw_core',
        ioDirectory: '../../../mobileclaw-core/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class MobileclawCoreBridgeApi extends BaseApi {
  Future<List<AgentEventDto>> crateFfiAgentSessionChat({
    required AgentSession that,
    required String input,
    required String system,
  });

  Future<AgentSession> crateFfiAgentSessionCreate({
    required AgentConfig config,
  });

  Future<void> crateFfiAgentSessionEmailAccountDelete({
    required AgentSession that,
    required String id,
  });

  Future<EmailAccountDto?> crateFfiAgentSessionEmailAccountLoad({
    required AgentSession that,
    required String id,
  });

  Future<void> crateFfiAgentSessionEmailAccountSave({
    required AgentSession that,
    required EmailAccountDto dto,
    required String password,
  });

  Future<List<MessageDto>> crateFfiAgentSessionHistory({
    required AgentSession that,
  });

  Future<void> crateFfiAgentSessionLoadSkillsFromDir({
    required AgentSession that,
    required String dir,
  });

  Future<BigInt> crateFfiAgentSessionMemoryCount({required AgentSession that});

  Future<bool> crateFfiAgentSessionMemoryForget({
    required AgentSession that,
    required String path,
  });

  Future<MemoryDocDto?> crateFfiAgentSessionMemoryGet({
    required AgentSession that,
    required String path,
  });

  Future<List<SearchResultDto>> crateFfiAgentSessionMemoryRecall({
    required AgentSession that,
    required String query,
    required BigInt limit,
    String? category,
    BigInt? since,
    BigInt? until,
  });

  Future<MemoryDocDto> crateFfiAgentSessionMemoryStore({
    required AgentSession that,
    required String path,
    required String content,
    required String category,
  });

  Future<void> crateFfiAgentSessionProviderDelete({
    required AgentSession that,
    required String id,
  });

  Future<ProviderConfigDto?> crateFfiAgentSessionProviderGetActive({
    required AgentSession that,
  });

  Future<List<ProviderConfigDto>> crateFfiAgentSessionProviderList({
    required AgentSession that,
  });

  Future<void> crateFfiAgentSessionProviderSave({
    required AgentSession that,
    required ProviderConfigDto config,
    String? apiKey,
  });

  Future<void> crateFfiAgentSessionProviderSetActive({
    required AgentSession that,
    required String id,
  });

  Future<List<SkillManifestDto>> crateFfiAgentSessionSkills({
    required AgentSession that,
  });

  Future<ProbeResultDto> crateFfiProviderProbe({
    required ProviderConfigDto config,
    String? apiKey,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AgentSession;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AgentSession;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_AgentSessionPtr;
}

class MobileclawCoreBridgeApiImpl extends MobileclawCoreBridgeApiImplPlatform
    implements MobileclawCoreBridgeApi {
  MobileclawCoreBridgeApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<List<AgentEventDto>> crateFfiAgentSessionChat({
    required AgentSession that,
    required String input,
    required String system,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
            that,
            serializer,
          );
          sse_encode_String(input, serializer);
          sse_encode_String(system, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_agent_event_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFfiAgentSessionChatConstMeta,
        argValues: [that, input, system],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiAgentSessionChatConstMeta => const TaskConstMeta(
    debugName: "AgentSession_chat",
    argNames: ["that", "input", "system"],
  );

  @override
  Future<AgentSession> crateFfiAgentSessionCreate({
    required AgentConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_agent_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFfiAgentSessionCreateConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiAgentSessionCreateConstMeta => const TaskConstMeta(
    debugName: "AgentSession_create",
    argNames: ["config"],
  );

  @override
  Future<void> crateFfiAgentSessionEmailAccountDelete({
    required AgentSession that,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
            that,
            serializer,
          );
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFfiAgentSessionEmailAccountDeleteConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiAgentSessionEmailAccountDeleteConstMeta =>
      const TaskConstMeta(
        debugName: "AgentSession_email_account_delete",
        argNames: ["that", "id"],
      );

  @override
  Future<EmailAccountDto?> crateFfiAgentSessionEmailAccountLoad({
    required AgentSession that,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
            that,
            serializer,
          );
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_email_account_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFfiAgentSessionEmailAccountLoadConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiAgentSessionEmailAccountLoadConstMeta =>
      const TaskConstMeta(
        debugName: "AgentSession_email_account_load",
        argNames: ["that", "id"],
      );

  @override
  Future<void> crateFfiAgentSessionEmailAccountSave({
    required AgentSession that,
    required EmailAccountDto dto,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
            that,
            serializer,
          );
          sse_encode_box_autoadd_email_account_dto(dto, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFfiAgentSessionEmailAccountSaveConstMeta,
        argValues: [that, dto, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiAgentSessionEmailAccountSaveConstMeta =>
      const TaskConstMeta(
        debugName: "AgentSession_email_account_save",
        argNames: ["that", "dto", "password"],
      );

  @override
  Future<List<MessageDto>> crateFfiAgentSessionHistory({
    required AgentSession that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_message_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateFfiAgentSessionHistoryConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiAgentSessionHistoryConstMeta =>
      const TaskConstMeta(
        debugName: "AgentSession_history",
        argNames: ["that"],
      );

  @override
  Future<void> crateFfiAgentSessionLoadSkillsFromDir({
    required AgentSession that,
    required String dir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
            that,
            serializer,
          );
          sse_encode_String(dir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFfiAgentSessionLoadSkillsFromDirConstMeta,
        argValues: [that, dir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiAgentSessionLoadSkillsFromDirConstMeta =>
      const TaskConstMeta(
        debugName: "AgentSession_load_skills_from_dir",
        argNames: ["that", "dir"],
      );

  @override
  Future<BigInt> crateFfiAgentSessionMemoryCount({required AgentSession that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFfiAgentSessionMemoryCountConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiAgentSessionMemoryCountConstMeta =>
      const TaskConstMeta(
        debugName: "AgentSession_memory_count",
        argNames: ["that"],
      );

  @override
  Future<bool> crateFfiAgentSessionMemoryForget({
    required AgentSession that,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFfiAgentSessionMemoryForgetConstMeta,
        argValues: [that, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiAgentSessionMemoryForgetConstMeta =>
      const TaskConstMeta(
        debugName: "AgentSession_memory_forget",
        argNames: ["that", "path"],
      );

  @override
  Future<MemoryDocDto?> crateFfiAgentSessionMemoryGet({
    required AgentSession that,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_memory_doc_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFfiAgentSessionMemoryGetConstMeta,
        argValues: [that, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiAgentSessionMemoryGetConstMeta =>
      const TaskConstMeta(
        debugName: "AgentSession_memory_get",
        argNames: ["that", "path"],
      );

  @override
  Future<List<SearchResultDto>> crateFfiAgentSessionMemoryRecall({
    required AgentSession that,
    required String query,
    required BigInt limit,
    String? category,
    BigInt? since,
    BigInt? until,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
            that,
            serializer,
          );
          sse_encode_String(query, serializer);
          sse_encode_usize(limit, serializer);
          sse_encode_opt_String(category, serializer);
          sse_encode_opt_box_autoadd_u_64(since, serializer);
          sse_encode_opt_box_autoadd_u_64(until, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_search_result_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFfiAgentSessionMemoryRecallConstMeta,
        argValues: [that, query, limit, category, since, until],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiAgentSessionMemoryRecallConstMeta =>
      const TaskConstMeta(
        debugName: "AgentSession_memory_recall",
        argNames: ["that", "query", "limit", "category", "since", "until"],
      );

  @override
  Future<MemoryDocDto> crateFfiAgentSessionMemoryStore({
    required AgentSession that,
    required String path,
    required String content,
    required String category,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          sse_encode_String(content, serializer);
          sse_encode_String(category, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_memory_doc_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFfiAgentSessionMemoryStoreConstMeta,
        argValues: [that, path, content, category],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiAgentSessionMemoryStoreConstMeta =>
      const TaskConstMeta(
        debugName: "AgentSession_memory_store",
        argNames: ["that", "path", "content", "category"],
      );

  @override
  Future<void> crateFfiAgentSessionProviderDelete({
    required AgentSession that,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
            that,
            serializer,
          );
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFfiAgentSessionProviderDeleteConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiAgentSessionProviderDeleteConstMeta =>
      const TaskConstMeta(
        debugName: "AgentSession_provider_delete",
        argNames: ["that", "id"],
      );

  @override
  Future<ProviderConfigDto?> crateFfiAgentSessionProviderGetActive({
    required AgentSession that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_provider_config_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFfiAgentSessionProviderGetActiveConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiAgentSessionProviderGetActiveConstMeta =>
      const TaskConstMeta(
        debugName: "AgentSession_provider_get_active",
        argNames: ["that"],
      );

  @override
  Future<List<ProviderConfigDto>> crateFfiAgentSessionProviderList({
    required AgentSession that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_provider_config_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFfiAgentSessionProviderListConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiAgentSessionProviderListConstMeta =>
      const TaskConstMeta(
        debugName: "AgentSession_provider_list",
        argNames: ["that"],
      );

  @override
  Future<void> crateFfiAgentSessionProviderSave({
    required AgentSession that,
    required ProviderConfigDto config,
    String? apiKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
            that,
            serializer,
          );
          sse_encode_box_autoadd_provider_config_dto(config, serializer);
          sse_encode_opt_String(apiKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFfiAgentSessionProviderSaveConstMeta,
        argValues: [that, config, apiKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiAgentSessionProviderSaveConstMeta =>
      const TaskConstMeta(
        debugName: "AgentSession_provider_save",
        argNames: ["that", "config", "apiKey"],
      );

  @override
  Future<void> crateFfiAgentSessionProviderSetActive({
    required AgentSession that,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
            that,
            serializer,
          );
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFfiAgentSessionProviderSetActiveConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiAgentSessionProviderSetActiveConstMeta =>
      const TaskConstMeta(
        debugName: "AgentSession_provider_set_active",
        argNames: ["that", "id"],
      );

  @override
  Future<List<SkillManifestDto>> crateFfiAgentSessionSkills({
    required AgentSession that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_skill_manifest_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateFfiAgentSessionSkillsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiAgentSessionSkillsConstMeta =>
      const TaskConstMeta(debugName: "AgentSession_skills", argNames: ["that"]);

  @override
  Future<ProbeResultDto> crateFfiProviderProbe({
    required ProviderConfigDto config,
    String? apiKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_provider_config_dto(config, serializer);
          sse_encode_opt_String(apiKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_probe_result_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateFfiProviderProbeConstMeta,
        argValues: [config, apiKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiProviderProbeConstMeta => const TaskConstMeta(
    debugName: "provider_probe",
    argNames: ["config", "apiKey"],
  );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AgentSession => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AgentSession => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  AgentSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AgentSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AgentSession
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AgentSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AgentSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AgentSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AgentSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AgentSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AgentConfig dco_decode_agent_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return AgentConfig(
      apiKey: dco_decode_opt_String(arr[0]),
      dbPath: dco_decode_String(arr[1]),
      secretsDbPath: dco_decode_String(arr[2]),
      encryptionKey: dco_decode_list_prim_u_8_strict(arr[3]),
      sandboxDir: dco_decode_String(arr[4]),
      httpAllowlist: dco_decode_list_String(arr[5]),
      model: dco_decode_opt_String(arr[6]),
      skillsDir: dco_decode_opt_String(arr[7]),
      logDir: dco_decode_opt_String(arr[8]),
      sessionDir: dco_decode_opt_String(arr[9]),
      contextWindow: arr[10] as int?,
      maxSessionMessages: arr[11] as int?,
    );
  }

  @protected
  AgentEventDto dco_decode_agent_event_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return AgentEventDto_TextDelta(text: dco_decode_String(raw[1]));
      case 1:
        return AgentEventDto_ToolCall(name: dco_decode_String(raw[1]));
      case 2:
        return AgentEventDto_ToolResult(
          name: dco_decode_String(raw[1]),
          success: dco_decode_bool(raw[2]),
        );
      case 3:
        return AgentEventDto_ContextStats(
          tokensBeforeTurn: dco_decode_i_64(raw[1]),
          tokensAfterPrune: dco_decode_i_64(raw[2]),
          messagesPruned: dco_decode_i_64(raw[3]),
          historyLen: dco_decode_i_64(raw[4]),
          pruningThreshold: dco_decode_i_64(raw[5]),
        );
      case 4:
        return AgentEventDto_TurnSummary(summary: dco_decode_String(raw[1]));
      case 5:
        return AgentEventDto_Done();
      default:
        throw Exception('Unknown AgentEventDto tag: ${raw[0]}');
    }
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AgentConfig dco_decode_box_autoadd_agent_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_agent_config(raw);
  }

  @protected
  EmailAccountDto dco_decode_box_autoadd_email_account_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_email_account_dto(raw);
  }

  @protected
  MemoryDocDto dco_decode_box_autoadd_memory_doc_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_memory_doc_dto(raw);
  }

  @protected
  ProviderConfigDto dco_decode_box_autoadd_provider_config_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_provider_config_dto(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  EmailAccountDto dco_decode_email_account_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return EmailAccountDto(
      id: dco_decode_String(arr[0]),
      smtpHost: dco_decode_String(arr[1]),
      smtpPort: dco_decode_i_32(arr[2]),
      imapHost: dco_decode_String(arr[3]),
      imapPort: dco_decode_i_32(arr[4]),
      username: dco_decode_String(arr[5]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AgentEventDto> dco_decode_list_agent_event_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_agent_event_dto).toList();
  }

  @protected
  List<MessageDto> dco_decode_list_message_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_message_dto).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ProviderConfigDto> dco_decode_list_provider_config_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_provider_config_dto).toList();
  }

  @protected
  List<SearchResultDto> dco_decode_list_search_result_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_search_result_dto).toList();
  }

  @protected
  List<SkillManifestDto> dco_decode_list_skill_manifest_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_skill_manifest_dto).toList();
  }

  @protected
  MemoryDocDto dco_decode_memory_doc_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return MemoryDocDto(
      id: dco_decode_String(arr[0]),
      path: dco_decode_String(arr[1]),
      content: dco_decode_String(arr[2]),
      category: dco_decode_String(arr[3]),
      createdAt: dco_decode_u_64(arr[4]),
      updatedAt: dco_decode_u_64(arr[5]),
    );
  }

  @protected
  MessageDto dco_decode_message_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MessageDto(
      role: dco_decode_String(arr[0]),
      content: dco_decode_String(arr[1]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  EmailAccountDto? dco_decode_opt_box_autoadd_email_account_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_email_account_dto(raw);
  }

  @protected
  MemoryDocDto? dco_decode_opt_box_autoadd_memory_doc_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_memory_doc_dto(raw);
  }

  @protected
  ProviderConfigDto? dco_decode_opt_box_autoadd_provider_config_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_provider_config_dto(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  ProbeResultDto dco_decode_probe_result_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ProbeResultDto(
      ok: dco_decode_bool(arr[0]),
      latencyMs: dco_decode_u_64(arr[1]),
      degraded: dco_decode_bool(arr[2]),
      error: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  ProviderConfigDto dco_decode_provider_config_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ProviderConfigDto(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      protocol: dco_decode_String(arr[2]),
      baseUrl: dco_decode_String(arr[3]),
      model: dco_decode_String(arr[4]),
      createdAt: dco_decode_i_64(arr[5]),
    );
  }

  @protected
  SearchResultDto dco_decode_search_result_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SearchResultDto(
      doc: dco_decode_memory_doc_dto(arr[0]),
      score: dco_decode_f_32(arr[1]),
    );
  }

  @protected
  SkillManifestDto dco_decode_skill_manifest_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SkillManifestDto(
      name: dco_decode_String(arr[0]),
      description: dco_decode_String(arr[1]),
      trust: dco_decode_String(arr[2]),
      keywords: dco_decode_list_String(arr[3]),
      allowedTools: dco_decode_list_String(arr[4]),
    );
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  AgentSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AgentSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AgentSession
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AgentSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AgentSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AgentSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AgentSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AgentSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AgentConfig sse_decode_agent_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_apiKey = sse_decode_opt_String(deserializer);
    var var_dbPath = sse_decode_String(deserializer);
    var var_secretsDbPath = sse_decode_String(deserializer);
    var var_encryptionKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_sandboxDir = sse_decode_String(deserializer);
    var var_httpAllowlist = sse_decode_list_String(deserializer);
    var var_model = sse_decode_opt_String(deserializer);
    var var_skillsDir = sse_decode_opt_String(deserializer);
    var var_logDir = sse_decode_opt_String(deserializer);
    var var_sessionDir = sse_decode_opt_String(deserializer);
    var var_contextWindow = sse_decode_opt_u_32(deserializer);
    var var_maxSessionMessages = sse_decode_opt_u_32(deserializer);
    return AgentConfig(
      apiKey: var_apiKey,
      dbPath: var_dbPath,
      secretsDbPath: var_secretsDbPath,
      encryptionKey: var_encryptionKey,
      sandboxDir: var_sandboxDir,
      httpAllowlist: var_httpAllowlist,
      model: var_model,
      skillsDir: var_skillsDir,
      logDir: var_logDir,
      sessionDir: var_sessionDir,
      contextWindow: var_contextWindow,
      maxSessionMessages: var_maxSessionMessages,
    );
  }

  @protected
  AgentEventDto sse_decode_agent_event_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_text = sse_decode_String(deserializer);
        return AgentEventDto_TextDelta(text: var_text);
      case 1:
        var var_name = sse_decode_String(deserializer);
        return AgentEventDto_ToolCall(name: var_name);
      case 2:
        var var_name = sse_decode_String(deserializer);
        var var_success = sse_decode_bool(deserializer);
        return AgentEventDto_ToolResult(name: var_name, success: var_success);
      case 3:
        return AgentEventDto_ContextStats(
          tokensBeforeTurn: sse_decode_i_64(deserializer),
          tokensAfterPrune: sse_decode_i_64(deserializer),
          messagesPruned: sse_decode_i_64(deserializer),
          historyLen: sse_decode_i_64(deserializer),
          pruningThreshold: sse_decode_i_64(deserializer),
        );
      case 4:
        return AgentEventDto_TurnSummary(
          summary: sse_decode_String(deserializer),
        );
      case 5:
        return AgentEventDto_Done();
      default:
        throw UnimplementedError('Unknown AgentEventDto tag: $tag_');
    }
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AgentConfig sse_decode_box_autoadd_agent_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_agent_config(deserializer));
  }

  @protected
  EmailAccountDto sse_decode_box_autoadd_email_account_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_email_account_dto(deserializer));
  }

  @protected
  MemoryDocDto sse_decode_box_autoadd_memory_doc_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_memory_doc_dto(deserializer));
  }

  @protected
  ProviderConfigDto sse_decode_box_autoadd_provider_config_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_provider_config_dto(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  EmailAccountDto sse_decode_email_account_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_smtpHost = sse_decode_String(deserializer);
    var var_smtpPort = sse_decode_i_32(deserializer);
    var var_imapHost = sse_decode_String(deserializer);
    var var_imapPort = sse_decode_i_32(deserializer);
    var var_username = sse_decode_String(deserializer);
    return EmailAccountDto(
      id: var_id,
      smtpHost: var_smtpHost,
      smtpPort: var_smtpPort,
      imapHost: var_imapHost,
      imapPort: var_imapPort,
      username: var_username,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AgentEventDto> sse_decode_list_agent_event_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AgentEventDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_agent_event_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<MessageDto> sse_decode_list_message_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MessageDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_message_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ProviderConfigDto> sse_decode_list_provider_config_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ProviderConfigDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_provider_config_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<SearchResultDto> sse_decode_list_search_result_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SearchResultDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_search_result_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<SkillManifestDto> sse_decode_list_skill_manifest_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SkillManifestDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_skill_manifest_dto(deserializer));
    }
    return ans_;
  }

  @protected
  MemoryDocDto sse_decode_memory_doc_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_category = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_u_64(deserializer);
    var var_updatedAt = sse_decode_u_64(deserializer);
    return MemoryDocDto(
      id: var_id,
      path: var_path,
      content: var_content,
      category: var_category,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  MessageDto sse_decode_message_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_role = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    return MessageDto(role: var_role, content: var_content);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    if (sse_decode_bool(deserializer)) {
      return sse_decode_u_32(deserializer);
    } else {
      return null;
    }
  }

  @protected
  void sse_encode_opt_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_u_32(self, serializer);
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  EmailAccountDto? sse_decode_opt_box_autoadd_email_account_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_email_account_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  MemoryDocDto? sse_decode_opt_box_autoadd_memory_doc_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_memory_doc_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProviderConfigDto? sse_decode_opt_box_autoadd_provider_config_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_provider_config_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProbeResultDto sse_decode_probe_result_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_latencyMs = sse_decode_u_64(deserializer);
    var var_degraded = sse_decode_bool(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return ProbeResultDto(
      ok: var_ok,
      latencyMs: var_latencyMs,
      degraded: var_degraded,
      error: var_error,
    );
  }

  @protected
  ProviderConfigDto sse_decode_provider_config_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_protocol = sse_decode_String(deserializer);
    var var_baseUrl = sse_decode_String(deserializer);
    var var_model = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    return ProviderConfigDto(
      id: var_id,
      name: var_name,
      protocol: var_protocol,
      baseUrl: var_baseUrl,
      model: var_model,
      createdAt: var_createdAt,
    );
  }

  @protected
  SearchResultDto sse_decode_search_result_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_doc = sse_decode_memory_doc_dto(deserializer);
    var var_score = sse_decode_f_32(deserializer);
    return SearchResultDto(doc: var_doc, score: var_score);
  }

  @protected
  SkillManifestDto sse_decode_skill_manifest_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_trust = sse_decode_String(deserializer);
    var var_keywords = sse_decode_list_String(deserializer);
    var var_allowedTools = sse_decode_list_String(deserializer);
    return SkillManifestDto(
      name: var_name,
      description: var_description,
      trust: var_trust,
      keywords: var_keywords,
      allowedTools: var_allowedTools,
    );
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    AgentSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AgentSessionImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    AgentSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AgentSessionImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    AgentSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AgentSessionImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAgentSession(
    AgentSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AgentSessionImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_agent_config(AgentConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.apiKey, serializer);
    sse_encode_String(self.dbPath, serializer);
    sse_encode_String(self.secretsDbPath, serializer);
    sse_encode_list_prim_u_8_strict(self.encryptionKey, serializer);
    sse_encode_String(self.sandboxDir, serializer);
    sse_encode_list_String(self.httpAllowlist, serializer);
    sse_encode_opt_String(self.model, serializer);
    sse_encode_opt_String(self.skillsDir, serializer);
    sse_encode_opt_String(self.logDir, serializer);
    sse_encode_opt_String(self.sessionDir, serializer);
    sse_encode_opt_u_32(self.contextWindow, serializer);
    sse_encode_opt_u_32(self.maxSessionMessages, serializer);
  }

  @protected
  void sse_encode_agent_event_dto(
    AgentEventDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case AgentEventDto_TextDelta(text: final text):
        sse_encode_i_32(0, serializer);
        sse_encode_String(text, serializer);
      case AgentEventDto_ToolCall(name: final name):
        sse_encode_i_32(1, serializer);
        sse_encode_String(name, serializer);
      case AgentEventDto_ToolResult(name: final name, success: final success):
        sse_encode_i_32(2, serializer);
        sse_encode_String(name, serializer);
        sse_encode_bool(success, serializer);
      case AgentEventDto_ContextStats(
          tokensBeforeTurn: final tokensBeforeTurn,
          tokensAfterPrune: final tokensAfterPrune,
          messagesPruned: final messagesPruned,
          historyLen: final historyLen,
          pruningThreshold: final pruningThreshold,
        ):
        sse_encode_i_32(3, serializer);
        sse_encode_i_64(tokensBeforeTurn, serializer);
        sse_encode_i_64(tokensAfterPrune, serializer);
        sse_encode_i_64(messagesPruned, serializer);
        sse_encode_i_64(historyLen, serializer);
        sse_encode_i_64(pruningThreshold, serializer);
      case AgentEventDto_TurnSummary(summary: final summary):
        sse_encode_i_32(4, serializer);
        sse_encode_String(summary, serializer);
      case AgentEventDto_Done():
        sse_encode_i_32(5, serializer);
    }
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_agent_config(
    AgentConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_agent_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_email_account_dto(
    EmailAccountDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_email_account_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_memory_doc_dto(
    MemoryDocDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_memory_doc_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_provider_config_dto(
    ProviderConfigDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_provider_config_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_email_account_dto(
    EmailAccountDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.smtpHost, serializer);
    sse_encode_i_32(self.smtpPort, serializer);
    sse_encode_String(self.imapHost, serializer);
    sse_encode_i_32(self.imapPort, serializer);
    sse_encode_String(self.username, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_agent_event_dto(
    List<AgentEventDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_agent_event_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_message_dto(
    List<MessageDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_message_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_provider_config_dto(
    List<ProviderConfigDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_provider_config_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_search_result_dto(
    List<SearchResultDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_search_result_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_skill_manifest_dto(
    List<SkillManifestDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_skill_manifest_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_memory_doc_dto(MemoryDocDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_String(self.category, serializer);
    sse_encode_u_64(self.createdAt, serializer);
    sse_encode_u_64(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_message_dto(MessageDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.role, serializer);
    sse_encode_String(self.content, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_email_account_dto(
    EmailAccountDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_email_account_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_memory_doc_dto(
    MemoryDocDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_memory_doc_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_provider_config_dto(
    ProviderConfigDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_provider_config_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_probe_result_dto(
    ProbeResultDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_u_64(self.latencyMs, serializer);
    sse_encode_bool(self.degraded, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_provider_config_dto(
    ProviderConfigDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.protocol, serializer);
    sse_encode_String(self.baseUrl, serializer);
    sse_encode_String(self.model, serializer);
    sse_encode_i_64(self.createdAt, serializer);
  }

  @protected
  void sse_encode_search_result_dto(
    SearchResultDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_memory_doc_dto(self.doc, serializer);
    sse_encode_f_32(self.score, serializer);
  }

  @protected
  void sse_encode_skill_manifest_dto(
    SkillManifestDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_String(self.trust, serializer);
    sse_encode_list_String(self.keywords, serializer);
    sse_encode_list_String(self.allowedTools, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class AgentSessionImpl extends RustOpaque implements AgentSession {
  // Not to be used by end users
  AgentSessionImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  AgentSessionImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: MobileclawCoreBridge
        .instance
        .api
        .rust_arc_increment_strong_count_AgentSession,
    rustArcDecrementStrongCount: MobileclawCoreBridge
        .instance
        .api
        .rust_arc_decrement_strong_count_AgentSession,
    rustArcDecrementStrongCountPtr: MobileclawCoreBridge
        .instance
        .api
        .rust_arc_decrement_strong_count_AgentSessionPtr,
  );

  /// Send a user message and return all events produced by one agent turn.
  Future<List<AgentEventDto>> chat({
    required String input,
    required String system,
  }) => MobileclawCoreBridge.instance.api.crateFfiAgentSessionChat(
    that: this,
    input: input,
    system: system,
  );

  /// Delete an email account and its stored password.
  Future<void> emailAccountDelete({required String id}) => MobileclawCoreBridge
      .instance
      .api
      .crateFfiAgentSessionEmailAccountDelete(that: this, id: id);

  /// Load an email account's configuration. Returns None if the account does not exist.
  /// The password is NOT returned — only the non-secret config fields.
  Future<EmailAccountDto?> emailAccountLoad({required String id}) =>
      MobileclawCoreBridge.instance.api.crateFfiAgentSessionEmailAccountLoad(
        that: this,
        id: id,
      );

  /// Save an email account configuration and its password.
  /// The password is encrypted with AES-256-GCM before storage.
  /// After this call, the password cannot be retrieved in plaintext via any FFI method.
  Future<void> emailAccountSave({
    required EmailAccountDto dto,
    required String password,
  }) => MobileclawCoreBridge.instance.api.crateFfiAgentSessionEmailAccountSave(
    that: this,
    dto: dto,
    password: password,
  );

  /// Return a snapshot of the conversation history.
  Future<List<MessageDto>> history() =>
      MobileclawCoreBridge.instance.api.crateFfiAgentSessionHistory(that: this);

  /// Load skills from a directory and replace the current skill manager.
  Future<void> loadSkillsFromDir({required String dir}) => MobileclawCoreBridge
      .instance
      .api
      .crateFfiAgentSessionLoadSkillsFromDir(that: this, dir: dir);

  /// Return the total number of memory documents.
  Future<BigInt> memoryCount() => MobileclawCoreBridge.instance.api
      .crateFfiAgentSessionMemoryCount(that: this);

  /// Delete a memory document. Returns true if it existed.
  Future<bool> memoryForget({required String path}) => MobileclawCoreBridge
      .instance
      .api
      .crateFfiAgentSessionMemoryForget(that: this, path: path);

  /// Retrieve a single memory document by path.
  Future<MemoryDocDto?> memoryGet({required String path}) =>
      MobileclawCoreBridge.instance.api.crateFfiAgentSessionMemoryGet(
        that: this,
        path: path,
      );

  /// Search the memory database and return ranked results.
  Future<List<SearchResultDto>> memoryRecall({
    required String query,
    required BigInt limit,
    String? category,
    BigInt? since,
    BigInt? until,
  }) => MobileclawCoreBridge.instance.api.crateFfiAgentSessionMemoryRecall(
    that: this,
    query: query,
    limit: limit,
    category: category,
    since: since,
    until: until,
  );

  /// Store a document in the memory database.
  Future<MemoryDocDto> memoryStore({
    required String path,
    required String content,
    required String category,
  }) => MobileclawCoreBridge.instance.api.crateFfiAgentSessionMemoryStore(
    that: this,
    path: path,
    content: content,
    category: category,
  );

  /// Delete a provider config (and its API key via ON DELETE CASCADE).
  Future<void> providerDelete({required String id}) => MobileclawCoreBridge
      .instance
      .api
      .crateFfiAgentSessionProviderDelete(that: this, id: id);

  /// Return the active provider config, or `None` if no active provider is set.
  Future<ProviderConfigDto?> providerGetActive() => MobileclawCoreBridge
      .instance
      .api
      .crateFfiAgentSessionProviderGetActive(that: this);

  /// Return all stored provider configs as DTOs.
  Future<List<ProviderConfigDto>> providerList() => MobileclawCoreBridge
      .instance
      .api
      .crateFfiAgentSessionProviderList(that: this);

  /// Save (upsert) a provider config and optionally store its API key encrypted.
  Future<void> providerSave({
    required ProviderConfigDto config,
    String? apiKey,
  }) => MobileclawCoreBridge.instance.api.crateFfiAgentSessionProviderSave(
    that: this,
    config: config,
    apiKey: apiKey,
  );

  /// Set the active provider by ID. Returns an error if the provider does not exist.
  Future<void> providerSetActive({required String id}) => MobileclawCoreBridge
      .instance
      .api
      .crateFfiAgentSessionProviderSetActive(that: this, id: id);

  /// Return the loaded skills as DTOs.
  Future<List<SkillManifestDto>> skills() =>
      MobileclawCoreBridge.instance.api.crateFfiAgentSessionSkills(that: this);
}
